[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = ['@solmate=lib/solmate/src']

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
seed = "0x1"

[invariant]
runs = 100
depth = 32
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
